sonar.projectKey=Team-Haruki_deck-service
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,_cpp_src/**,target/**,coverage/**
sonar.coverageReportPaths=coverage/sonar-coverage.xml
